// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"hcs-agent/internal/biz"
	"hcs-agent/internal/data"
	"hcs-agent/internal/handler"
	"hcs-agent/internal/router"
	"hcs-agent/internal/server"
	"hcs-agent/internal/serviece"
	"hcs-agent/pkg/app"
	"hcs-agent/pkg/config"
	"hcs-agent/pkg/log"
	"hcs-agent/pkg/server/chatbox"
	"hcs-agent/pkg/server/http"
	"hcs-agent/pkg/sid"
)

// Injectors from wire.go:

func NewChatBoxWire(configConfig *config.Config, logger *log.Logger) (*app.Client, func(), error) {
	chatBoxServer := server.NewChatBoxServer(configConfig, logger)
	sidSid := sid.NewSid()
	serviceService := service.NewService(logger, sidSid)
	esDb := data.NewEsDb(configConfig, logger)
	demoRepo := data.NewDemoRepo(esDb, logger)
	demo := biz.NewDemoUseCase(demoRepo, logger)
	demoService := service.NewDemoService(serviceService, demo)
	demoHandler := handler.NewDemoHandler(demoService)
	routerDeps := router.RouterDeps{
		Logger:      logger,
		Config:      configConfig,
		DemoHandler: demoHandler,
	}
	httpServer := server.NewHTTPServer(routerDeps)
	client := newApp(chatBoxServer, httpServer)
	return client, func() {
	}, nil
}

// wire.go:

func newApp(chatBoxServer *chatbox.Server, httpServer *http.Server) *app.Client {
	return app.NewApp(app.WithServer(chatBoxServer), app.WithName("chat box"))
}
